'use client';
import { FormEvent, useEffect, useState } from 'react';
import { services } from '@/lib/content';
import { site } from '@/lib/site';
export function Booking(){
  const [service,setService]=useState(services[0].slug),[date,setDate]=useState(''),[zip,setZip]=useState(''),[ready,setReady]=useState(false),[minDate,setMinDate]=useState('');
  useEffect(()=>{const now=new Date();setMinDate(`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`);const s=new URLSearchParams(location.search).get('service');if(s&&services.some(v=>v.slug===s))setService(s);},[]);
  const label=services.find(s=>s.slug===service)?.title;
  const email=`${site.emailHref}?subject=${encodeURIComponent('Inspection scheduling request')}&body=${encodeURIComponent(`Service: ${label}\nPreferred date: ${date}\nProperty ZIP: ${zip}\n\nProperty address:\nName:\nPhone:\n\nPlease confirm availability and pricing.`)}`;
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setReady(true);}
  return <div className="hs-booking"><div>{ready?<div className="hs-booking-summary"><h2>Ready for your next step.</h2><div className="hs-detail"><div><strong>{label}</strong><p>Preferred date: {date}<br/>Property ZIP: {zip}</p></div></div><p>These preferences are not a reservation. Choose an available appointment and enter your property details in the scheduling portal, or email the team.</p><a className="hs-primary" href={site.bookingUrl} target="_blank" rel="noreferrer">Open online scheduler ↗</a><a href={email}>Email these preferences →</a><button onClick={()=>setReady(false)}>← Edit preferences</button></div>:<><h2>Your inspection preferences</h2><form onSubmit={submit}><label>Inspection service<select value={service} onChange={e=>setService(e.target.value)}>{services.map(s=><option value={s.slug} key={s.slug}>{s.title}</option>)}</select></label><label>Preferred date<input type="date" required min={minDate} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Property ZIP code<input inputMode="numeric" autoComplete="postal-code" pattern="[0-9]{5}" maxLength={5} required title="Enter a five-digit US ZIP code" placeholder="77008" value={zip} onChange={e=>setZip(e.target.value)}/></label><button type="submit" className="hs-primary">Continue to scheduling →</button><p>Availability and pricing are confirmed in our scheduling portal. No appointment is created by this form.</p></form></>}</div><aside className="hs-booking-aside"><p className="hs-eyebrow">LET’S MAKE IT SIMPLE</p><h2>Local experts.<br/>Clear next steps.</h2><p>We serve Greater Houston and surrounding communities. Have a tight option period or a question about the right inspection? Call our team.</p><a href={site.phoneHref}>{site.phone}</a><a href={site.emailHref}>{site.email}</a><p>{site.hours}</p><a className="hs-primary" href={site.bookingUrl} target="_blank" rel="noreferrer">View online scheduling ↗</a></aside></div>;
}
